title = "Rastijahti"
contentDir = "content/fi"
#The namge of the language, it that language (not in English if it's not English)
languageName = "Suomi"
languageCode = "fi"
beforeColon = ""
# Weight used for sorting.
# 10 for English
# Other languages from 100 to 999, alphabetical order using languageCode.
weight = 100
description = """
  Rastijahti."""
# Number format : <negative>|<decimal>|<grouping>
# Ex. for -1 2345.67 -> "-|.| "
# Doc: https://gohugo.io/functions/numfmt/
