[[main]]
name = "Ohjelma"
weight = 30
identifier = "program"
url = "/fi/program/"

[[main]]
name = "Tulosarkisto"
weight = 40
identifier = "arkiv"
url = "/fi/arkiv/"

[[main]]
name = "Statistikka"
weight = 50
identifier = "statistik"
