baseURL = "http://skarmjakten.fi/"
languageCode = "sv"
defaultContentLanguage = "sv"
title = "Skärmjakten"
theme = "ananke"

[languages]
  [languages.sv]
    title = "Skärmjakten"
    weight = 1
    contentDir = "content/sv"
  [languages.fi]
    title = "Rastijahti"
    weight = 2
    contentDir = "content/fi"

[menu]

  [[menu.main]]
    identifier = "program"
    name = "program"
    pre = "<i class='fa fa-heart'></i>"
    url = "/program/"
    weight = -110

  [[menu.main]]
    name = "resultatarkiv"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/resultat/"
    weight = -100
