# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Build statistik

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["test"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.108.0
    steps:
      - name: Install statistik CLI
        run: |
          wget -O ${{ runner.temp }}/statistik https://github.com/Skarmjakten/statistik/releases/download/v0.1/statistik \
          && chmod +x ${{ runner.temp }}/statistik
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build statistik
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          ${{runner.temp}}/statistik 2022
